//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abouts
    {
        public int AboutID { get; set; }
        public string AboutDetails { get; set; }
        public string AboutDetails1 { get; set; }
        public string AboutImage { get; set; }
        public string AboutImage1 { get; set; }
    }
}
